"""
seed_dummy_variants.py
Generates dummy variants from the 13 real Eskan Bank assets to pad the register.
Run AFTER seed_eskan_register.py.
"""
import db

variants = [
    # ── CBS variants ──────────────────────────────────────────────────────
    {
        'asset_id': 'AR-CBS-002',
        'system_name': 'Core Banking System - DR Instance',
        'data_category': 'Financial Data',
        'description': 'Disaster Recovery instance of the Core Banking System maintained at the secondary data centre for business continuity.',
        'business_function': 'IT / Operations',
        'data_owner': 'Head of Retail Banking / Head of Corporate Banking',
        'custodian': 'AGM Enterprise Digital Optimization',
        'data_location': 'Secondary Data Centre - DR Environment',
        'data_classification': 'Restricted',
        'data_sensitivity': 'High (PII + Financial Data)',
        'business_criticality': 'Critical',
        'who_has_access': 'IT Infrastructure team, authorised DR team members',
        'access_mechanism': 'RBAC; restricted DR access; MFA required',
        'security_controls': 'Network segmentation, MFA, SIEM logging, periodic DR drills, access reviews',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': '10 years (as per Customer & Regulatory Retention Requirements)',
        'backup_retention': 'Continuous replication; daily snapshots',
        'disposal_method': 'Secure deletion / crypto-wipe in line with Data Disposal Procedure',
        'primary_use': 'Business continuity and disaster recovery for core banking operations',
        'risk_rating': 'High',
        'key_risks': 'DR failover failure, data inconsistency, unauthorised DR access, replication lag',
        'policy_reference': 'IS-POL-001; BCP-POL-001; CBB OM-5.5',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.17.1',
        'last_review_date': '2025-01-15',
        'remarks': 'Annual DR test required; review tied to CBS-001 cycle',
    },
    {
        'asset_id': 'AR-CBS-003',
        'system_name': 'Core Banking System - Reporting Module',
        'data_category': 'Financial Data',
        'description': 'Reporting and analytics module of the Core Banking System used for generating regulatory, management and audit reports.',
        'business_function': 'Finance / Compliance / Risk',
        'data_owner': 'Head of Retail Banking / Head of Corporate Banking',
        'custodian': 'AGM Enterprise Digital Optimization',
        'data_location': 'Core Banking System - Reporting Layer',
        'data_classification': 'Restricted',
        'data_sensitivity': 'High (PII + Financial Data)',
        'business_criticality': 'High',
        'who_has_access': 'Finance, Compliance, Risk, and senior management with approved access',
        'access_mechanism': 'Role-Based Access Control; report-level permissions; MFA',
        'security_controls': 'RBAC, audit logs, read-only access for report users, DLP',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': '10 years (as per Regulatory Retention Requirements)',
        'backup_retention': 'Covered by CBS-001 backup schedule',
        'disposal_method': 'Secure deletion in line with Data Disposal Procedure',
        'primary_use': 'Regulatory reporting, management dashboards, audit evidence, CBB submissions',
        'risk_rating': 'High',
        'key_risks': 'Unauthorised access to financial reports, data leakage, report manipulation',
        'policy_reference': 'IS-POL-001; CBB OM-5.5',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.8.2',
        'last_review_date': '2025-05-15',
        'remarks': 'Annual review cycle',
    },
    # ── HR variants ───────────────────────────────────────────────────────
    {
        'asset_id': 'AR-HR-002',
        'system_name': 'Payroll Processing System',
        'data_category': 'Personal Data',
        'description': 'Dedicated payroll processing system managing salary calculations, deductions, allowances and payslip generation for all bank employees.',
        'business_function': 'Human Resources / Finance',
        'data_owner': 'Senior Manager HR',
        'custodian': 'HRMS Systems Support (ADG) / IT',
        'data_location': 'Payroll System Server',
        'data_classification': 'Restricted',
        'data_sensitivity': 'High (Sensitive PII + Payroll + Financial)',
        'business_criticality': 'High',
        'who_has_access': 'Payroll team, Finance, authorised HR management',
        'access_mechanism': 'RBAC; dual-authorisation for payroll runs; MFA',
        'security_controls': 'Dual-control approvals, RBAC, audit logs, SIEM monitoring, segregation of duties',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': 'Employment period + 5 years (or per legal policy)',
        'backup_retention': 'Regular backups per HR data policy',
        'disposal_method': 'Secure destruction of electronic records; disposal logged',
        'primary_use': 'Monthly payroll processing, salary disbursement, payslip generation, statutory deductions',
        'risk_rating': 'High',
        'key_risks': 'Payroll fraud, unauthorised salary changes, data leakage, system manipulation',
        'policy_reference': 'IS-POL-001; HR-POL-002',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.8.2; Bahrain Labour Law',
        'last_review_date': '2025-06-22',
        'remarks': 'Annual review cycle',
    },
    {
        'asset_id': 'AR-HR-003',
        'system_name': 'Attendance & Leave Management System',
        'data_category': 'Personal Data',
        'description': 'System tracking employee attendance, leave requests, approvals and time records for all bank staff.',
        'business_function': 'Human Resources',
        'data_owner': 'Senior Manager HR',
        'custodian': 'HRMS Systems Support (ADG) / IT',
        'data_location': 'HR Attendance System',
        'data_classification': 'Internal',
        'data_sensitivity': 'Medium (Employee Attendance Data)',
        'business_criticality': 'Medium',
        'who_has_access': 'All staff (self-service), HR team, line managers',
        'access_mechanism': 'AD authentication; manager approval workflow; RBAC',
        'security_controls': 'RBAC, audit logs, manager approval controls, periodic access reviews',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Partial',
        'retention_period': 'Employment period + 3 years',
        'backup_retention': 'Regular backups',
        'disposal_method': 'Secure deletion per HR data retention policy',
        'primary_use': 'Attendance tracking, leave management, workforce planning, payroll input',
        'risk_rating': 'Medium',
        'key_risks': 'Unauthorised leave approval, attendance manipulation, privacy concerns',
        'policy_reference': 'IS-POL-001; HR-POL-002',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.8.1',
        'last_review_date': '2025-07-11',
        'remarks': 'Annual review cycle',
    },
    # ── DMS variants ──────────────────────────────────────────────────────
    {
        'asset_id': 'AR-DMS-002',
        'system_name': 'Document Management System - Compliance Archive',
        'data_category': 'Regulatory Data',
        'description': 'Dedicated compliance archive within the DMS storing regulatory submissions, CBB correspondence and compliance evidence documents.',
        'business_function': 'Compliance / Legal',
        'data_owner': 'AGM Compliance',
        'custodian': 'IT',
        'data_location': 'DMS Compliance Archive Module',
        'data_classification': 'Restricted',
        'data_sensitivity': 'High (Regulatory + Legal Documentation)',
        'business_criticality': 'High',
        'who_has_access': 'Compliance team, Legal, senior management with documented approval',
        'access_mechanism': 'RBAC; compliance-level access provisioning; MFA',
        'security_controls': 'RBAC, immutable audit trail, DLP, change control, backup policy',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': '10 years minimum (as per Regulatory Retention Requirements)',
        'backup_retention': 'Regular backups; off-site copy maintained',
        'disposal_method': 'Secure destruction only upon legal authorisation; disposal logged',
        'primary_use': 'Regulatory compliance evidence, CBB audit support, legal document retention',
        'risk_rating': 'High',
        'key_risks': 'Document tampering, premature disposal, unauthorised access to regulatory evidence',
        'policy_reference': 'IS-POL-001; COMP-POL-001; CBB OM-5.5',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.18.1',
        'last_review_date': '2025-07-30',
        'remarks': 'Annual review cycle',
    },
    # ── Network & Infrastructure ──────────────────────────────────────────
    {
        'asset_id': 'AR-NET-001',
        'system_name': 'Network Infrastructure (Core Switches & Routers)',
        'data_category': 'Operational / Log Data',
        'description': 'Core network switching and routing infrastructure forming the backbone of the bank\'s internal network, including LAN, WAN and DMZ segments.',
        'business_function': 'IT Infrastructure',
        'data_owner': 'AGM Enterprise Digital Optimization',
        'custodian': 'IT Infrastructure Team',
        'data_location': 'Primary Data Centre & Branch Locations',
        'data_classification': 'Restricted',
        'data_sensitivity': 'High (Network Configuration + Traffic Data)',
        'business_criticality': 'Critical',
        'who_has_access': 'IT Infrastructure team, Network administrators',
        'access_mechanism': 'Privileged access management (PAM); MFA; out-of-band management',
        'security_controls': 'Network segmentation, VLAN controls, IDS/IPS, SIEM, firewall rules, privileged access management',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Partial',
        'retention_period': 'Network logs: 1 year minimum; configuration records: until superseded + 3 years',
        'backup_retention': 'Configuration backups daily; DR site maintained',
        'disposal_method': 'Secure configuration wipe; hardware disposal per data destruction procedure',
        'primary_use': 'Internal network connectivity, internet access, inter-branch communication, system integration',
        'risk_rating': 'High',
        'key_risks': 'Network intrusion, DDoS, misconfiguration, unauthorised access, network outage',
        'policy_reference': 'IS-POL-001; NET-POL-001; CBB OM-5.5',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.13.1',
        'last_review_date': '2025-09-06',
        'remarks': 'Annual review cycle',
    },
    {
        'asset_id': 'AR-NET-002',
        'system_name': 'Firewall & Perimeter Security Systems',
        'data_category': 'Operational / Log Data',
        'description': 'Perimeter firewall and security appliances protecting the bank\'s network boundary, including next-generation firewalls, web application firewalls and DLP solutions.',
        'business_function': 'IT / Information Security',
        'data_owner': 'AGM Enterprise Digital Optimization',
        'custodian': 'IT Infrastructure / Information Security Team',
        'data_location': 'Primary Data Centre - DMZ & Perimeter',
        'data_classification': 'Restricted',
        'data_sensitivity': 'High (Security Configuration + Log Data)',
        'business_criticality': 'Critical',
        'who_has_access': 'Information Security team, senior IT administrators',
        'access_mechanism': 'Privileged access management; MFA; change management approval required',
        'security_controls': 'Change management controls, dual-authorisation for rule changes, SIEM integration, IDS/IPS, periodic rule reviews',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': 'Security logs: 1 year minimum; rule configurations: until superseded + 3 years',
        'backup_retention': 'Configuration backups after every change; off-site copy',
        'disposal_method': 'Secure configuration wipe; hardware disposal per data destruction procedure',
        'primary_use': 'Perimeter defence, traffic filtering, DLP enforcement, intrusion prevention, internet gateway control',
        'risk_rating': 'High',
        'key_risks': 'Misconfiguration allowing breach, firewall bypass, rule bloat, zero-day exploitation',
        'policy_reference': 'IS-POL-001; NET-POL-001; CBB OM-5.5',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.13.1; ISO 27001 A.12.4',
        'last_review_date': '2025-09-25',
        'remarks': 'Annual review cycle; quarterly firewall rule reviews',
    },
    # ── Email & Communication ─────────────────────────────────────────────
    {
        'asset_id': 'AR-COM-001',
        'system_name': 'Corporate Email System (Exchange / O365)',
        'data_category': 'Internal Communications',
        'description': 'Corporate email platform managing all internal and external electronic communications for bank staff.',
        'business_function': 'All Departments',
        'data_owner': 'Respective AGMs',
        'custodian': 'IT Infrastructure Team',
        'data_location': 'On-Premise Exchange / Microsoft 365',
        'data_classification': 'Internal',
        'data_sensitivity': 'Medium-High (Internal Communications + Potentially Sensitive Attachments)',
        'business_criticality': 'High',
        'who_has_access': 'All bank staff with assigned mailboxes',
        'access_mechanism': 'AD authentication; MFA for external access; RBAC for admin functions',
        'security_controls': 'Anti-spam, anti-phishing, DLP policies, email encryption for sensitive communications, audit logging, MFA',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': 'As per Business & Regulatory Retention Requirements (typically 5 years)',
        'backup_retention': 'Daily backups; litigation hold where applicable',
        'disposal_method': 'Secure deletion per email retention policy; legal hold override',
        'primary_use': 'Internal and external business communications, document sharing, notifications',
        'risk_rating': 'Medium',
        'key_risks': 'Phishing attacks, data leakage via email, business email compromise, unauthorised access to mailboxes',
        'policy_reference': 'IS-POL-001; EMAIL-POL-001',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.13.2',
        'last_review_date': '2026-02-24',
        'remarks': 'Annual review cycle',
    },
    # ── Security Systems ──────────────────────────────────────────────────
    {
        'asset_id': 'AR-SEC-001',
        'system_name': 'SIEM Platform',
        'data_category': 'Operational / Log Data',
        'description': 'Security Information and Event Management platform aggregating and correlating security logs from all bank systems for threat detection and incident response.',
        'business_function': 'Information Security',
        'data_owner': 'AGM Enterprise Digital Optimization',
        'custodian': 'IT / Information Security Team',
        'data_location': 'Security Operations - SIEM Server',
        'data_classification': 'Restricted',
        'data_sensitivity': 'High (Security Logs + Incident Data)',
        'business_criticality': 'Critical',
        'who_has_access': 'Information Security team, senior IT management',
        'access_mechanism': 'Privileged access; MFA; strict RBAC; need-to-know basis',
        'security_controls': 'Tamper-proof logging, strict access controls, network segmentation, backup & retention controls, SOC processes',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': 'As per Security Logging & Regulatory Retention Requirements (typically 1–7 years)',
        'backup_retention': 'Immutable log storage; off-site backup',
        'disposal_method': 'Secure deletion / sanitisation per security disposal procedures',
        'primary_use': 'Threat detection, incident response, forensic investigations, compliance monitoring, audit evidence',
        'risk_rating': 'High',
        'key_risks': 'Compromise of security logs, attacker hiding activity, unauthorised access, manipulation of evidence',
        'policy_reference': 'IS-POL-001; INC-POL-001; CBB OM-5.5',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.12.4; ISO 27001 A.16.1',
        'last_review_date': '2025-01-25',
        'remarks': 'Annual review cycle',
    },
    {
        'asset_id': 'AR-SEC-002',
        'system_name': 'Privileged Access Management (PAM) System',
        'data_category': 'Operational / Log Data',
        'description': 'PAM solution managing, monitoring and recording all privileged access sessions to critical bank systems and infrastructure.',
        'business_function': 'IT / Information Security',
        'data_owner': 'AGM Enterprise Digital Optimization',
        'custodian': 'IT / Information Security Team',
        'data_location': 'PAM Server - Primary Data Centre',
        'data_classification': 'Restricted',
        'data_sensitivity': 'High (Privileged Credentials + Session Recordings)',
        'business_criticality': 'Critical',
        'who_has_access': 'IT administrators; access strictly on need-to-know; reviewed quarterly',
        'access_mechanism': 'PAM-controlled access; session recording; MFA mandatory; just-in-time provisioning',
        'security_controls': 'Session recording, credential vaulting, MFA, just-in-time access, quarterly access reviews, SIEM integration',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': 'Session recordings: 1 year minimum; access logs: 3 years',
        'backup_retention': 'Daily backups; credential vault replicated to DR',
        'disposal_method': 'Secure deletion per security data disposal procedure',
        'primary_use': 'Privileged session management, credential vaulting, privileged access monitoring and recording',
        'risk_rating': 'High',
        'key_risks': 'Compromise of privileged credentials, insider threat, PAM bypass, credential theft',
        'policy_reference': 'IS-POL-001; PAM-POL-001; CBB OM-5.5',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.9.4; CIS Controls',
        'last_review_date': '2025-08-18',
        'remarks': 'Annual review cycle; quarterly access reviews',
    },
    # ── Backup & DR ───────────────────────────────────────────────────────
    {
        'asset_id': 'AR-BCK-001',
        'system_name': 'Enterprise Backup & Recovery System',
        'data_category': 'Operational / Log Data',
        'description': 'Enterprise backup solution managing scheduled backups of all critical bank systems, databases and file shares to on-site and off-site storage.',
        'business_function': 'IT Infrastructure',
        'data_owner': 'AGM Enterprise Digital Optimization',
        'custodian': 'IT Infrastructure Team',
        'data_location': 'Primary Data Centre + Off-site Backup Facility',
        'data_classification': 'Restricted',
        'data_sensitivity': 'High (Contains copies of all classified data)',
        'business_criticality': 'Critical',
        'who_has_access': 'IT Infrastructure team; backup administrators',
        'access_mechanism': 'RBAC; MFA; privileged access for restore operations; dual-authorisation for deletions',
        'security_controls': 'Encryption of backup data, RBAC, audit logging, off-site replication, periodic restore testing',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': 'As per individual system retention policies; minimum 90 days for operational backups',
        'backup_retention': 'Daily, weekly, monthly and annual backup sets maintained',
        'disposal_method': 'Secure erasure of expired backup media; certificate of destruction required',
        'primary_use': 'Data recovery, business continuity, DR failover support, compliance data retention',
        'risk_rating': 'High',
        'key_risks': 'Backup failure, ransomware targeting backups, restore failure during incident, inadequate retention',
        'policy_reference': 'IS-POL-001; BCP-POL-001; CBB OM-5.5',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.12.3; ISO 27001 A.17.1',
        'last_review_date': '2025-11-02',
        'remarks': 'Annual review; quarterly restore tests mandatory',
    },
    # ── Customer Data ─────────────────────────────────────────────────────
    {
        'asset_id': 'AR-CRM-001',
        'system_name': 'Customer Relationship Management (CRM) System',
        'data_category': 'Personal Data',
        'description': 'CRM platform managing customer interactions, relationship history, service requests and communication logs for retail and corporate banking customers.',
        'business_function': 'Retail Banking / Corporate Banking / Operations',
        'data_owner': 'AGM Commercial & Institutional Banking',
        'custodian': 'IT Development / Infrastructure Teams',
        'data_location': 'CRM Platform Server',
        'data_classification': 'Confidential',
        'data_sensitivity': 'High (PII + Financial Relationship Data)',
        'business_criticality': 'High',
        'who_has_access': 'Relationship managers, branch staff, customer service team, authorised management',
        'access_mechanism': 'RBAC; AD authentication; MFA for remote access; customer-level data segregation',
        'security_controls': 'RBAC, data segregation by customer, audit logs, DLP, SIEM monitoring, periodic access reviews',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': 'As per Customer Data & Regulatory Retention Requirements (typically 10 years)',
        'backup_retention': 'Daily backups; DR copy maintained',
        'disposal_method': 'Secure deletion / sanitisation as per data disposal procedure',
        'primary_use': 'Customer relationship management, service request tracking, interaction history, cross-selling support',
        'risk_rating': 'High',
        'key_risks': 'Unauthorised access to customer data, data leakage, identity theft risk, PDPL non-compliance',
        'policy_reference': 'IS-POL-001; CBB OM-5.5; Bahrain PDPL',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.8.2; Bahrain PDPL',
        'last_review_date': '2026-04-03',
        'remarks': 'Annual review cycle',
    },
    # ── Compliance & Audit ────────────────────────────────────────────────
    {
        'asset_id': 'AR-AUD-001',
        'system_name': 'Internal Audit Management System',
        'data_category': 'Regulatory Data',
        'description': 'System managing internal audit plans, findings, recommendations, management responses and follow-up tracking for all bank departments.',
        'business_function': 'Internal Audit',
        'data_owner': 'Chief Internal Auditor',
        'custodian': 'IT / Internal Audit Team',
        'data_location': 'Audit Management System Server',
        'data_classification': 'Restricted',
        'data_sensitivity': 'High (Audit Findings + Sensitive Internal Controls Data)',
        'business_criticality': 'High',
        'who_has_access': 'Internal Audit team, senior management, Board Audit Committee (read-only)',
        'access_mechanism': 'RBAC; strict need-to-know access; MFA',
        'security_controls': 'RBAC, immutable audit records, strict access controls, audit trail of all changes',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': '10 years minimum (regulatory requirement for audit records)',
        'backup_retention': 'Regular backups; off-site copy',
        'disposal_method': 'Secure deletion only upon legal authorisation; disposal logged',
        'primary_use': 'Internal audit planning, finding management, recommendation tracking, regulatory compliance evidence',
        'risk_rating': 'High',
        'key_risks': 'Tampering with audit findings, unauthorised disclosure of audit results, data loss',
        'policy_reference': 'IS-POL-001; AUDIT-POL-001; CBB OM-5.5',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.18.2; IIA Standards',
        'last_review_date': '2025-12-29',
        'remarks': 'Annual review cycle',
    },
]

print(f"\nInserting {len(variants)} dummy variant assets...")

for a in variants:
    db.execute("""
        INSERT INTO assets (
            asset_id, system_name, data_category, description,
            business_function, data_owner, custodian, data_classification, data_location,
            who_has_access, access_mechanism, security_controls,
            encryption_in_transit, encryption_at_rest,
            retention_period, backup_retention, disposal_method,
            primary_use, policy_reference, control_mapping, last_review_date, remarks,
            data_sensitivity, business_criticality, risk_rating, key_risks,
            created_by
        ) VALUES (
            %s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s
        )
    """, (
        a['asset_id'], a['system_name'], a['data_category'], a['description'],
        a['business_function'], a['data_owner'], a['custodian'],
        a['data_classification'], a['data_location'],
        a['who_has_access'], a['access_mechanism'], a['security_controls'],
        a['encryption_in_transit'], a['encryption_at_rest'],
        a['retention_period'], a['backup_retention'], a['disposal_method'],
        a['primary_use'], a['policy_reference'], a['control_mapping'],
        a['last_review_date'], a['remarks'],
        a['data_sensitivity'], a['business_criticality'], a['risk_rating'], a['key_risks'],
        'system'
    ))
    print(f"  ✓ {a['asset_id']} — {a['system_name']}")

print(f"\nDone. {len(variants)} assets inserted. Total register: 13 + {len(variants)} = {13 + len(variants)} assets.")