"""
seed_eskan_register.py
Seeds the assets table with Eskan Bank's actual Information Asset Register
based on the register provided by the industry mentor.
"""
import db

assets = [
    {
        'asset_id': 'AR-CBS-001',
        'system_name': 'Core Banking System (CBS)',
        'data_category': 'Financial Data',
        'description': 'Core system managing all customer loan accounts, mortgage processing, financial operations and regulatory reporting.',
        'business_function': 'Retail Banking, Operations',
        'data_owner': 'Head of Retail Banking / Head of Corporate Banking',
        'custodian': 'AGM Enterprise Digital Optimization',
        'data_location': 'Core Banking System (CBS)',
        'data_classification': 'Restricted',
        'data_sensitivity': 'High (PII + Financial Data)',
        'business_criticality': 'Critical',
        'who_has_access': 'Bank staff with approved CBS roles (branch, operations, finance, risk)',
        'access_mechanism': 'Role-Based Access Control (RBAC); periodic access reviews (yearly)',
        'security_controls': 'Network firewalls, MFA, strong password policy, session timeout, SIEM logging & alerting, DLP, change management, NDAs for third parties',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': '10 years (as per Customer & Regulatory Retention Requirements)',
        'backup_retention': 'Daily backups; DR replicas maintained',
        'disposal_method': 'Secure deletion / crypto-wipe in line with Data Disposal Procedure',
        'primary_use': 'Customer onboarding, account servicing, loan processing, financial operations, regulatory reporting',
        'risk_rating': 'High',
        'key_risks': 'Data breach, unauthorized access, privilege misuse, inadequate monitoring, system compromise',
        'policy_reference': 'IS-POL-001; CBB OM-5.5',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.8.2; ISO 27001 A.9.4',
        'last_review_date': '2025-01-15',
        'remarks': 'Annual review cycle or more frequent based on risk',
    },
    {
        'asset_id': 'AR-HR-001',
        'system_name': 'HRMS',
        'data_category': 'Personal Data',
        'description': 'Human Resources Management System storing employee personal and employment data, payroll, medical history and attendance information.',
        'business_function': 'Human Resources',
        'data_owner': 'Senior Manager HR',
        'custodian': 'HRMS Systems Support (ADG) / IT',
        'data_location': 'HRMS; Payroll System; Attendance System; HR Shared Folders',
        'data_classification': 'Restricted',
        'data_sensitivity': 'High (Sensitive PII + Payroll + Medical)',
        'business_criticality': 'High',
        'who_has_access': 'HR staff, Payroll team, authorised management',
        'access_mechanism': 'RBAC; HR onboarding/offboarding workflow; MFA (where supported)',
        'security_controls': 'RBAC, password policy enforcement, SIEM monitoring, NDAs; secure file shares, HR access governance',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': 'Employment period + 5 years (or per legal policy)',
        'backup_retention': 'Regular backups per HR data policy',
        'disposal_method': 'Secure destruction of electronic and physical records; disposal logged',
        'primary_use': 'HR administration, payroll processing, performance management, compliance reporting',
        'risk_rating': 'High',
        'key_risks': 'Privacy breach; identity theft; unauthorized disclosure of medical or payroll data; privilege misuse',
        'policy_reference': 'IS-POL-001; HR-POL-002',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.8.2; Bahrain PDPL',
        'last_review_date': '2025-06-03',
        'remarks': 'Annual review cycle',
    },
    {
        'asset_id': 'AR-PHY-001',
        'system_name': 'Physical Records Archive',
        'data_category': 'Operational / Log Data',
        'description': 'Physical hardcopy archive of customer and internal records stored on-site and off-site.',
        'business_function': 'All Business Departments',
        'data_owner': 'Respective AGMs of Department',
        'custodian': 'Records Management / Branch Operations',
        'data_location': 'Physical Archive Storage (On-site & Off-site)',
        'data_classification': 'Restricted',
        'data_sensitivity': 'High (PII + Financial + Sensitive Internal)',
        'business_criticality': 'High',
        'who_has_access': 'Authorised staff with physical access',
        'access_mechanism': 'Physical keys, access logs, restricted archive rooms',
        'security_controls': 'Locked cabinets, controlled archive rooms, CCTV, fire safety controls, physical access logs, disposal procedure',
        'encryption_in_transit': 'No',
        'encryption_at_rest': 'No',
        'retention_period': 'As per Records Retention Schedule & Regulatory Requirements',
        'backup_retention': 'Off-site storage for DR',
        'disposal_method': 'Secure shredding / certified physical destruction',
        'primary_use': 'Customer servicing support, compliance, audit evidence preservation',
        'risk_rating': 'High',
        'key_risks': 'Loss/theft of documents; unauthorised physical access; fire/water damage; improper disposal',
        'policy_reference': 'IS-POL-001; REC-POL-003',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.11.2',
        'last_review_date': '2025-10-14',
        'remarks': 'Annual review cycle',
    },
    {
        'asset_id': 'AR-DMS-001',
        'system_name': 'Document Management System (DMS)',
        'data_category': 'Regulatory Data',
        'description': 'Platform for storing and managing scanned customer documents including KYC, IDs, contracts and forms.',
        'business_function': 'All Customer-Facing Departments (Retail Banking, Operations, Compliance)',
        'data_owner': 'AGM Commercial & Institutional Banking / Compliance (depending on document type)',
        'custodian': 'IT',
        'data_location': 'DMS Platform (Document Repository)',
        'data_classification': 'Restricted',
        'data_sensitivity': 'High (PII + Financial Documentation)',
        'business_criticality': 'High',
        'who_has_access': 'Authorised business users and management roles with documented approval',
        'access_mechanism': 'RBAC; documented access provisioning; MFA (if supported)',
        'security_controls': 'RBAC, DLP, change control, backup policy, NDAs, segregation of duties',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': 'As per Customer Data & Regulatory Retention Schedules (e.g. 10 years depending on document type)',
        'backup_retention': 'Regular backups per document retention policy',
        'disposal_method': 'Secure destruction of digital documents via sanitisation; disposal logged',
        'primary_use': 'Customer onboarding, verification, KYC, compliance review, audit evidence',
        'risk_rating': 'High',
        'key_risks': 'Data breach, unauthorized access, document tampering, improper retention/disposal',
        'policy_reference': 'IS-POL-001; COMP-POL-001',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.8.3; ISO 27001 A.18.1',
        'last_review_date': '2025-01-20',
        'remarks': 'Annual review cycle',
    },
    {
        'asset_id': 'AR-PORT-001',
        'system_name': 'Portal System',
        'data_category': 'Internal Operations',
        'description': 'Corporate intranet portal for disseminating approved policies, procedures and internal communications across all departments.',
        'business_function': 'All Departments',
        'data_owner': 'Respective Policy Owners / AGMS',
        'custodian': 'IT / Information Security',
        'data_location': 'Corporate Portal / Intranet System',
        'data_classification': 'Internal',
        'data_sensitivity': 'Medium',
        'business_criticality': 'Medium',
        'who_has_access': 'All staff with approved portal access',
        'access_mechanism': 'AD authentication, RBAC, controlled publishing workflow',
        'security_controls': 'RBAC, change control workflow, audit logs, secure hosting, access reviews',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Partial',
        'retention_period': 'Until superseded + regulatory archival requirement',
        'backup_retention': 'Regular backups',
        'disposal_method': 'Secure deletion of outdated documents as per information handling & disposal procedure',
        'primary_use': 'Dissemination of approved policies, procedures, communication, and governance content',
        'risk_rating': 'Medium',
        'key_risks': 'Outdated content, unauthorized modification, accidental disclosure',
        'policy_reference': 'IS-POL-001',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.7.2',
        'last_review_date': '2025-12-10',
        'remarks': 'Annual review cycle',
    },
    {
        'asset_id': 'AR-FS-001',
        'system_name': 'Enterprise File Shares',
        'data_category': 'Internal Operations',
        'description': 'On-premise file servers and DR replicas storing departmental shared folders including operational documents, reports and business data.',
        'business_function': 'All Departments',
        'data_owner': 'Respective AGMs',
        'custodian': 'IT Infrastructure Team',
        'data_location': 'On-Premise File Servers & DR Replicas',
        'data_classification': 'Restricted',
        'data_sensitivity': 'Medium',
        'business_criticality': 'High',
        'who_has_access': 'AD Groups / Department Users with approved access',
        'access_mechanism': 'RBAC, File Share NTFS Permissions; periodic access reviews',
        'security_controls': 'NTFS permissions, RBAC, SIEM monitoring, backups, DR replication, least privilege, periodic reviews',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': 'As per Business & Regulatory Retention Requirements',
        'backup_retention': 'Daily backups; DR replicas',
        'disposal_method': 'Secure deletion & media sanitisation as per disposal procedure',
        'primary_use': 'Daily operations, document storage, collaboration, reporting',
        'risk_rating': 'Medium',
        'key_risks': 'Unauthorized access, accidental deletion, data leakage, improper access provisioning',
        'policy_reference': 'IS-POL-001',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.8.1',
        'last_review_date': '2026-03-15',
        'remarks': 'Annual review cycle',
    },
    {
        'asset_id': 'AR-RP-001',
        'system_name': 'Roaming Profiles Server',
        'data_category': 'Internal Operations',
        'description': 'Windows File Server hosting roaming profiles containing user profile data including My Documents and desktop content.',
        'business_function': 'All Departments (End Users)',
        'data_owner': 'Respective AGMs',
        'custodian': 'IT Infrastructure – Windows Server Team',
        'data_location': 'Windows File Server Hosting Roaming Profiles',
        'data_classification': 'Restricted',
        'data_sensitivity': 'Medium',
        'business_criticality': 'High',
        'who_has_access': 'End users with assigned domain accounts',
        'access_mechanism': 'AD authentication; NTFS permissions, RBAC, periodic access reviews',
        'security_controls': 'NTFS permissions, RBAC, anti-malware, backups, SIEM monitoring, least privilege, folder redirection policies',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': 'As per Data Retention Policy for workstation/user data',
        'backup_retention': 'Regular backups',
        'disposal_method': 'Secure deletion & media sanitisation as per disposal procedure',
        'primary_use': 'User workspace data, storage of day-to-day working files synced via roaming profile mechanism',
        'risk_rating': 'Medium',
        'key_risks': 'Accidental deletion, malware infection, unauthorized access, profile corruption, data leakage',
        'policy_reference': 'IS-POL-001',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.8.1',
        'last_review_date': '2026-02-05',
        'remarks': 'Annual review cycle',
    },
    {
        'asset_id': 'AR-RFE-001',
        'system_name': 'RFE System',
        'data_category': 'Financial Data',
        'description': 'Procurement and Vendor Management Platform managing order information, supplier contact details, payment details and vendor contracts.',
        'business_function': 'Procurement / Finance',
        'data_owner': 'AGM Support Services',
        'custodian': 'AGM Enterprise Digital Optimization',
        'data_location': 'RFE System (Procurement & Vendor Management Platform)',
        'data_classification': 'Restricted',
        'data_sensitivity': 'Medium-High (Financial + Supplier Sensitive Data)',
        'business_criticality': 'High',
        'who_has_access': 'Administration team, Finance team, authorised management',
        'access_mechanism': 'RBAC, AD authentication; workflow-based access control',
        'security_controls': 'RBAC, MFA (if supported), audit logs, SIEM monitoring, workflow approvals, least-privilege access, regular access reviews',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': 'As per Procurement & Financial Records Retention Policy (typically 7–10 years)',
        'backup_retention': 'Regular backups',
        'disposal_method': 'Secure deletion / media sanitisation as per disposal procedure',
        'primary_use': 'Vendor management, order processing, contract handling, supplier communication, payment processing',
        'risk_rating': 'High',
        'key_risks': 'Unauthorized access; manipulation of orders/payment info; supplier data leakage; contract misuse',
        'policy_reference': 'IS-POL-001; PROC-POL-001',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.8.2; ISO 27001 A.15',
        'last_review_date': '2025-01-10',
        'remarks': 'Annual review cycle',
    },
    {
        'asset_id': 'AR-EFS-001',
        'system_name': 'EFS System',
        'data_category': 'Financial Data',
        'description': 'Remedial and Collections Platform managing collection data and overdue account tracking for customers.',
        'business_function': 'Collections / Risk Management',
        'data_owner': 'AGM Risk Management',
        'custodian': 'IT Infrastructure Team',
        'data_location': 'EFS System (Remedial & Collections Platform)',
        'data_classification': 'Restricted',
        'data_sensitivity': 'High (Financial + Sensitive Customer Data)',
        'business_criticality': 'High',
        'who_has_access': 'Collections officers, Risk team, authorised management',
        'access_mechanism': 'RBAC; workflow-based access; AD authentication; periodic access reviews',
        'security_controls': 'RBAC, MFA (if supported), audit logs, SIEM monitoring, workflow approvals, data segregation, periodic user access reviews',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': 'As per Customer Financial Records Retention Requirements (typically 10 years)',
        'backup_retention': 'Regular backups',
        'disposal_method': 'Secure deletion / sanitisation as per disposal procedure',
        'primary_use': 'Customer remedial processing, collections management, overdue account tracking, regulatory and audit reporting',
        'risk_rating': 'High',
        'key_risks': 'Unauthorized access; data leakage; manipulation of remedial actions; privacy breach',
        'policy_reference': 'IS-POL-001; RISK-POL-001',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.8.2',
        'last_review_date': None,
        'remarks': 'Annual review cycle',
    },
    {
        'asset_id': 'AR-FMS-001',
        'system_name': 'Facility Management System (FMS)',
        'data_category': 'Operational / Log Data',
        'description': 'System managing commercial leased property rental information, supplier and landlord contact details, rental payment information and contract documents.',
        'business_function': 'EPC',
        'data_owner': 'GM EPC',
        'custodian': 'IT Development / Infrastructure Teams',
        'data_location': 'Facility Management System (FMS)',
        'data_classification': 'Restricted',
        'data_sensitivity': 'Medium-High (Financial + Contractual Data)',
        'business_criticality': 'Medium',
        'who_has_access': 'Security team, Finance team, EPC, authorised management',
        'access_mechanism': 'RBAC; AD authentication; workflow-based access control',
        'security_controls': 'RBAC, audit logs, workflow approvals, least-privilege access, SIEM monitoring, secure file shares, periodic access reviews',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': 'As per Property, Contract & Financial Records Retention Policy (typically 7–10 years)',
        'backup_retention': 'Regular backups',
        'disposal_method': 'Secure deletion / media sanitisation as per disposal procedure',
        'primary_use': 'Property lease management, contract administration, supplier communication, rental payment processing',
        'risk_rating': 'Medium',
        'key_risks': 'Unauthorized access; manipulation of rental/payment details; contract data leakage; operational disruption',
        'policy_reference': 'IS-POL-001; FAC-POL-001',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.8.1',
        'last_review_date': '2025-11-21',
        'remarks': 'Annual review cycle',
    },
    {
        'asset_id': 'AR-PTS-001',
        'system_name': 'Payment Transfer System (SWIFT / EFTS)',
        'data_category': 'Financial Data',
        'description': 'SWIFT Alliance / EFTS Platform managing payment transfer instructions, customer and supplier payment data and transaction confirmations.',
        'business_function': 'Operations / Finance / Treasury',
        'data_owner': 'AGM Support Services',
        'custodian': 'IT Development / Infrastructure Teams',
        'data_location': 'SWIFT Alliance / EFTS Platform',
        'data_classification': 'Restricted',
        'data_sensitivity': 'High (Financial Transactions + Sensitive Customer Data)',
        'business_criticality': 'Critical',
        'who_has_access': 'Operations staff, Treasury, Finance, authorised management',
        'access_mechanism': 'RBAC; AD authentication; SWIFT role-based access; dual-control workflow',
        'security_controls': 'Dual-control approvals, RBAC, MFA (if supported), SWIFT CSP controls, network segmentation, audit logs, secure message signing',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': 'As per Financial Transaction Retention Requirements (typically 10 years)',
        'backup_retention': 'Daily backups; DR maintained',
        'disposal_method': 'Secure deletion / media sanitisation as per disposal procedure',
        'primary_use': 'Domestic & international payment processing, settlement, reconciliation, regulatory reporting',
        'risk_rating': 'High',
        'key_risks': 'Fraud risk, unauthorized transfers; interception of payment messages; manipulation of confirmations; data leakage',
        'policy_reference': 'IS-POL-001; SWIFT-CSP-001',
        'control_mapping': 'CBB OM-5.5; SWIFT CSP; ISO 27001 A.8.2',
        'last_review_date': '2025-01-05',
        'remarks': 'Annual review cycle',
    },
    {
        'asset_id': 'AR-EON-001',
        'system_name': 'Eskan Online Banking Portal',
        'data_category': 'Personal Data',
        'description': 'Customer-facing online banking portal providing access to customer profile data, payment data, IBAN information, due amounts and instalment data.',
        'business_function': 'Retail Banking / Operations',
        'data_owner': 'AGM Commercial & Institutional Banking',
        'custodian': 'IT Development / Infrastructure Teams',
        'data_location': 'Eskan Online Banking Portal',
        'data_classification': 'Restricted',
        'data_sensitivity': 'High (Sensitive PII + Financial Data)',
        'business_criticality': 'Critical',
        'who_has_access': 'Customers (self-service), Operations, Finance, authorised support roles',
        'access_mechanism': 'Secure login, MFA, RBAC, API-controlled access',
        'security_controls': 'MFA, RBAC, encryption, SIEM monitoring, fraud detection controls, secure coding, periodic access reviews',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': 'As per Customer & Regulatory Retention Requirements (typically 10 years)',
        'backup_retention': 'Daily backups; DR maintained',
        'disposal_method': 'Secure deletion / data sanitisation as per disposal procedure',
        'primary_use': 'Online banking services, balance checks, payments, instalment inquiries, customer servicing',
        'risk_rating': 'High',
        'key_risks': 'Fraud, unauthorized access, data leakage, manipulation of IBAN/payment instructions',
        'policy_reference': 'IS-POL-001; CBB OM-5.5',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.9.4; OWASP Top 10',
        'last_review_date': None,
        'remarks': 'Annual review cycle',
    },
    {
        'asset_id': 'AR-BAITY-001',
        'system_name': 'Baity System',
        'data_category': 'Personal Data',
        'description': 'Web portal and mobile app managing customer information, housing unit listings from real estate developers and payment information for Eskan housing services.',
        'business_function': 'Retail Banking / Housing Services / Real Estate',
        'data_owner': 'AGM Commercial & Institutional Banking',
        'custodian': 'Klabs / Enterprise Communication / IT',
        'data_location': 'Baity Web Portal & App',
        'data_classification': 'Restricted',
        'data_sensitivity': 'High (PII + Financial + Property Data)',
        'business_criticality': 'High',
        'who_has_access': 'Customers, Retail Banking, Housing Services Team, authorised management',
        'access_mechanism': 'Secure login (customer); RBAC (internal users); AD Authentication (staff)',
        'security_controls': 'MFA (customer & staff where supported), RBAC, secure coding practices, network segmentation, periodic access reviews',
        'encryption_in_transit': 'Yes',
        'encryption_at_rest': 'Yes',
        'retention_period': 'As per Customer & Regulatory Retention Requirements (typically 10 years)',
        'backup_retention': 'Regular backups; DR maintained',
        'disposal_method': 'Secure deletion / sanitisation per disposal procedure',
        'primary_use': 'Customer housing eligibility checks, property browsing, instalment/payment management, developer listing management',
        'risk_rating': 'High',
        'key_risks': 'Unauthorized access; data leakage; manipulation of payment or property data; fraudulent access',
        'policy_reference': 'IS-POL-001; CBB OM-5.5',
        'control_mapping': 'CBB OM-5.5; ISO 27001 A.9.4; Bahrain PDPL',
        'last_review_date': '2026-01-17',
        'remarks': 'Annual review cycle',
    },
]

print(f"\nInserting {len(assets)} assets from Eskan Bank Information Asset Register...")

for a in assets:
    db.execute("""
        INSERT INTO assets (
            asset_id, system_name, data_category, description,
            business_function, data_owner, custodian, data_location,
            data_classification, data_sensitivity, business_criticality,
            who_has_access, access_mechanism, security_controls,
            encryption_in_transit, encryption_at_rest,
            retention_period, backup_retention, disposal_method,
            primary_use, risk_rating, key_risks,
            policy_reference, control_mapping, last_review_date, remarks,
            created_by
        ) VALUES (
            %s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s
        )
    """, (
        a['asset_id'], a['system_name'], a['data_category'], a['description'],
        a['business_function'], a['data_owner'], a['custodian'], a['data_location'],
        a['data_classification'], a['data_sensitivity'], a['business_criticality'],
        a['who_has_access'], a['access_mechanism'], a['security_controls'],
        a['encryption_in_transit'], a['encryption_at_rest'],
        a['retention_period'], a['backup_retention'], a['disposal_method'],
        a['primary_use'], a['risk_rating'], a['key_risks'],
        a['policy_reference'], a['control_mapping'], a['last_review_date'], a['remarks'],
        'system'
    ))
    print(f"  ✓ {a['asset_id']} — {a['system_name']}")

print(f"\nDone. {len(assets)} assets inserted.")